In [1]:
import numpy as np

arr=[6,7,8,9]
print(type(arr))

<class 'list'>


In [4]:
a=np.array(arr)
print(type(a))
print(a.shape)

print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
(4,)
int32
1


In [10]:
np.random.random((2,3))

array([[0.58716581, 0.47733129, 0.80195307],
       [0.50245766, 0.27806507, 0.30122132]])

In [18]:
c=np.array([[1,2,3],[1,2,3]])
d=np.array([[1,2,3],[1,2,3],[6,7,8]])
c**2

array([[1, 4, 9],
       [1, 4, 9]], dtype=int32)

In [20]:
d[2,:]

array([6, 7, 8])

In [33]:
import pandas as pd

url='https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw=true'
fuel_data=pd.read_csv(url)
fuel_data.describe(include='all')

record_id  utility_id_ferc1   report_year  \
count                   29523      29523.000000  29523.000000   
unique                  29523               NaN           NaN   
top     f1_fuel_1994_12_1_0_7               NaN           NaN   
freq                        1               NaN           NaN   
mean                      NaN        118.601836   2005.806050   
std                       NaN         74.178353      7.025483   
min                       NaN          1.000000   1994.000000   
25%                       NaN         55.000000   2000.000000   
50%                       NaN        122.000000   2006.000000   
75%                       NaN        176.000000   2012.000000   
max                       NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [31]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [39]:
fuel_data.groupby('fuel_unit')['fuel_unit'].count()

fuel_data[['fuel_unit']]=fuel_data[['fuel_unit']].fillna(value='mcf')

In [40]:
fuel_data.isnull().sum()

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [49]:
fuel_data.groupby('report_year')['report_year'].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [48]:

fuel_data.groupby('fuel_type_code_pudl').first()

record_id  utility_id_ferc1  report_year  \
fuel_type_code_pudl                                                          
coal                  f1_fuel_1994_12_1_0_7                 1         1994   
gas                  f1_fuel_1994_12_2_0_10                 2         1994   
nuclear               f1_fuel_1994_12_2_1_1                 2         1994   
oil                   f1_fuel_1994_12_6_0_2                 6         1994   
other                f1_fuel_1994_12_11_0_6                11         1994   
waste                 f1_fuel_1994_12_9_0_3                 9         1994   

                     plant_name_ferc1 fuel_unit  fuel_qty_burned  \
fuel_type_code_pudl                                                
coal                         rockport       ton        5377489.0   
gas                         chickasaw       mcf          40533.0   
nuclear              joseph m. farley       kgU           2260.0   
oil                      clinch river       bbl           6510.0   
other                      w.f. wyman       bbl          55652.0   
waste                    b.l. england       ton           2438.0   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
coal                           16.590000                     18.590   
gas                             1.000000                      2.770   
nuclear                         0.064094                     28.770   
oil                             5.875338                     32.130   
other                           0.149719                     14.685   
waste                           0.015939                     34.180   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
coal                                       18.530                1.121  
gas                                         2.770                2.570  
nuclear                                     0.000                0.450  
oil                                        23.444                5.469  
other                                      15.090                2.335  
waste                                      34.180                1.072

In [50]:
fuel_data.duplicated().any()

False

In [1]:
import pandas as pd
import numpy as np

In [2]:
food=pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin-1')

In [3]:
food.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [4]:
lst=[[1,2,3],[1,2,3],[1,2,3]]
col=[3553,3535,3535]
df=pd.DataFrame(food)
gk=df.groupby(by=['Area'])
gk.first()

Area Code  Item Code             Item  \
Area                                                                 
Algeria                              4       2501       Population   
Angola                               7       2501       Population   
Benin                               53       2501       Population   
Botswana                            20       2501       Population   
Burkina Faso                       233       2501       Population   
Cabo Verde                          35       2501       Population   
Cameroon                            32       2501       Population   
Central African Republic            37       2501       Population   
Chad                                39       2501       Population   
Comoros                             45       2781   Fish, Body Oil   
Congo                               46       2501       Population   
Côte d'Ivoire                      107       2501       Population   
Djibouti                            72       2501       Population   
Egypt                               59       2501       Population   
Eswatini                           209       2501       Population   
Ethiopia                           238       2501       Population   
Ethiopia PDR                        62       2782  Fish, Liver Oil   
Gabon                               74       2501       Population   
Gambia                              75       2501       Population   
Ghana                               81       2501       Population   
Guinea                              90       2501       Population   
Guinea-Bissau                      175       2501       Population   
Kenya                              114       2501       Population   
Lesotho                            122       2501       Population   
Liberia                            123       2501       Population   
Madagascar                         129       2501       Population   
Malawi                             130       2501       Population   
Mali                               133       2501       Population   
Mauritania                         136       2501       Population   
Mauritius                          137       2501       Population   
Morocco                            143       2501       Population   
Mozambique                         144       2501       Population   
Namibia                            147       2501       Population   
Niger                              158       2501       Population   
Nigeria                            159       2501       Population   
Rwanda                             184       2501       Population   
Sao Tome and Principe              193       2501       Population   
Senegal                            195       2501       Population   
Seychelles                         196       2781   Fish, Body Oil   
Sierra Leone                       197       2501       Population   
South Africa                       202       2501       Population   
Sudan                              276       2501       Population   
Sudan (former)                     206       2781   Fish, Body Oil   
Togo                               217       2501       Population   
Tunisia                            222       2501       Population   
Uganda                             226       2501       Population   
United Republic of Tanzania        215       2501       Population   
Zambia                             251       2501       Population   
Zimbabwe                           181       2501       Population   

                             Element Code                        Element  \
Area                                                                       
Algeria                               511  Total Population - Both sexes   
Angola                                511  Total Population - Both sexes   
Benin                                 511  Total Population - Both sexes   
Botswana                              511  Total Population - Both sexes   
Bu

In [5]:
food.describe()

Area Code     Item Code  Element Code          Y2014          Y2015  \
count  60943.000000  60943.000000  60943.000000   59354.000000   59395.000000   
mean     134.265576   2687.176706   3814.856456     134.196282     135.235966   
std       72.605709    146.055739   2212.007033    1567.663696    1603.403984   
min        4.000000   2501.000000    511.000000   -1796.000000   -3161.000000   
25%       74.000000   2562.000000    684.000000       0.000000       0.000000   
50%      136.000000   2630.000000   5142.000000       0.090000       0.080000   
75%      195.000000   2775.000000   5511.000000       8.340000       8.460000   
max      276.000000   2961.000000   5911.000000  176405.000000  181137.000000   

               Y2016          Y2017          Y2018  
count   59408.000000   59437.000000   59507.000000  
mean      136.555222     140.917765     143.758381  
std      1640.007194    1671.862359    1710.782658  
min     -3225.000000   -1582.000000   -3396.000000  
25%         0.000000       0.000000       0.000000  
50%         0.080000       0.100000       0.070000  
75%         8.430000       9.000000       9.000000  
max    185960.000000  190873.000000  195875.000000